// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYBHtwcOJz4TwAjnB-zbDdO-kw0hm2O0',
    appId: '1:695403266833:web:53f9ae4c681696252502b0',
    messagingSenderId: '695403266833',
    projectId: 'food-friend-1',
    authDomain: 'food-friend-1.firebaseapp.com',
    storageBucket: 'food-friend-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDua41Ro07sxzDXB6a8oWYvbCSU8d2mUBQ',
    appId: '1:695403266833:android:42b6adaebcb3500c2502b0',
    messagingSenderId: '695403266833',
    projectId: 'food-friend-1',
    storageBucket: 'food-friend-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Yoq4Lf7MJK9loMIULM_alddzC4d3Sps',
    appId: '1:695403266833:ios:6d2e34ae27a7a3db2502b0',
    messagingSenderId: '695403266833',
    projectId: 'food-friend-1',
    storageBucket: 'food-friend-1.appspot.com',
    iosBundleId: 'com.example.foodFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Yoq4Lf7MJK9loMIULM_alddzC4d3Sps',
    appId: '1:695403266833:ios:7c70650cf6c1addd2502b0',
    messagingSenderId: '695403266833',
    projectId: 'food-friend-1',
    storageBucket: 'food-friend-1.appspot.com',
    iosBundleId: 'com.example.foodFriend.RunnerTests',
  );
}
